In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive

In [32]:
from pathlib import Path
import pandas as pd
import os
import sklearn
from sklearn.preprocessing import LabelEncoder

In [34]:
print("Pandas Version:", pd.__version__)
print("Scikit-Learn Version", sklearn.__version__)

Pandas Version: 2.2.2
Scikit-Learn Version 1.6.1

In [ ]:
#Current Working Path
try:
    BASE_DIR = Path(__file__).resolve().parent.parent
except NameError:
    BASE_DIR = Path.cwd()

#dataset root
DATA_DIR = Path("/content/drive/MyDrive/Datasets/Image Dataset/data")

In [9]:
#load the training csv dataset & display the 1st 5 rows
train_df = pd.read_csv(DATA_DIR / "Training_set.csv")
train_df.head()

      filename                     label
0  Image_1.jpg          SOUTHERN DOGFACE
1  Image_2.jpg                    ADONIS
2  Image_3.jpg            BROWN SIPROETA
3  Image_4.jpg                   MONARCH
4  Image_5.jpg  GREEN CELLED CATTLEHEART

In [21]:
train_df['image_path'] = train_df['filename'].apply(
    lambda x: os.path.join(DATA_DIR, "train", x)
)

In [22]:
train_df.sample(5)

,filename,label,image_path
6270,Image_6271.jpg,COPPER TAIL,/content/drive/MyDrive/Datasets/Image Dataset/...
2801,Image_2802.jpg,LARGE MARBLE,/content/drive/MyDrive/Datasets/Image Dataset/...
3217,Image_3218.jpg,DANAID EGGFLY,/content/drive/MyDrive/Datasets/Image Dataset/...
4,Image_5.jpg,GREEN CELLED CATTLEHEART,/content/drive/MyDrive/Datasets/Image Dataset/...
4117,Image_4118.jpg,PURPLE HAIRSTREAK,/content/drive/MyDrive/Datasets/Image Dataset/...

In [23]:
#checking NAN values
train_df.isna().sum()

filename      0
label         0
image_path    0
dtype: int64

In [24]:
#checking duplicates
train_df.duplicated().sum()

np.int64(0)

In [25]:
# Check the distribution of classes in the target column
train_df['label'].value_counts()

label
MOURNING CLOAK    131
SLEEPY ORANGE     107
ATALA             100
BROWN SIPROETA     99
SCARCE SWALLOW     97
                 ...
AMERICAN SNOOT     74
GOLD BANDED        73
MALACHITE          73
CRIMSON PATCH      72
WOOD SATYR         71
Name: count, Length: 75, dtype: int64

In [27]:
# Print the minimum and maximum class frequencies for label column
print(f"Minimum frequency: {train_df['label'].value_counts().min()}")
print(f"Maximum frequency: {train_df['label'].value_counts().max()}")

Minimum frequency: 71
Maximum frequency: 131

Sufficient images in each class; Ok for training

In [31]:
# Check for any missing images by verifying if the paths exist
missing_files = train_df[~train_df['image_path'].apply(os.path.exists)]
print("Missing Count:",len(missing_files))

Missing Count: 0

In [35]:
#label encoding for label column
label_en = LabelEncoder()
train_df['encoded'] = label_en.fit_transform(train_df['label'])

In [38]:
train_df[['label', 'encoded']].head()

                      label  encoded
0          SOUTHERN DOGFACE       66
1                    ADONIS        0
2            BROWN SIPROETA       12
3                   MONARCH       44
4  GREEN CELLED CATTLEHEART       33